### ISSUE TITLE
Add CI Workflow to test coverage on multiple platforms (MacOS, Linux, Windows)

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#1157]
Either a) Update covecov CI to run on multiple platforms or b) Add a workflow to test on mac, linux, windows (can test on each independently)

Multiple platform example
```
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --workspace --all-targets

      - name: Install cargo-tarpaulin
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: cargo install cargo-tarpaulin

      - name: Run tarpaulin for coverage
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: cargo tarpaulin --out Xml

      - name: Upload to Codecov
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
```

TBH, we probably *don't* need to run Codecov, clippy, or anything else that is tied to that sort of thing on multiple platforms, but I do want to make sure we run tests (i.e cargo tests as a CI) on all three platforms. 

Easiest would be to just add another OS to ci.yml as above, but IMHO it might be better to break out into a separate YAML file for each platform so it's a separate CI test (that way they can run simultaneously).
