### ISSUE TITLE
Add macos-13 to CI build matrix

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#1196]
We are now testing on macos arm and windows, but the macos intel is failing. I believe that the correct os name to add is `macos-13`

Add macos-13 to the build matrix and figure out the failure. Maybe we need to install rust manually. Not sure if the juice is worth the squeeze as every year we will have less and less users on it, but putting up a ticket regardless.

**Comment by stacksjb** [comment]
According to my notes, the way to implement arm and intel testing would be like this:

```
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Include macOS
        architecture: [x86_64, arm64]  # Add both x86_64 and arm64 for Intel and ARM

    runs-on: ${{ matrix.os }}  # Dynamically selects the OS from the matrix
```

I will test and confirm.
