### ISSUE TITLE
Reduce CI times

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#1225]
Now that you've got CI building for multiple platforms it would be great to get the times down

Before:

![Image](https://github.com/user-attachments/assets/254f075a-179d-41c3-b27d-9498519c41fd)

After: 

![Image](https://github.com/user-attachments/assets/e41925cd-7941-4853-bd52-dc734b66bc4a)

Our total CI build time has gone from under 2 minutes to almost 7. There might be some caching optimizations. One thing I saw on first pass is that we are not using the architecture in the cache key

```yaml
      - name: Cache Cargo dependencies
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
```

I assume we need a different cache for different architectures as well. 

Also, we should make sure that `cargo-nextest` is being cached. Going through all the builds here it doesn't look like any of them are being successfully cached. This could greatly bring down our times!
